# Eureka - disabled
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# JWT production
spring.security.oauth2.resource-server.jwt.issuer-uri=https://sso.isums.pro/realms/isums

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

spring.grpc.client.channels.house.address=dns:///house-service:1010
spring.grpc.client.channels.house.negotiation-type=plaintext
spring.grpc.client.channels.user.address=dns:///user-service:1012
spring.grpc.client.channels.user.negotiation-type=plaintext
spring.grpc.client.channels.payment.address=dns:///payment-service:1013
spring.grpc.client.channels.payment.negotiation-type=plaintext

app.contract.view-url=${APP_CONTRACT_VIEW_URL:https://outsystem.isums.pro/contracts}

# Log
spring.jpa.show-sql=false
